name: Build and Deploy via FTP

on:
  push:
    branches:
      - main # ou a branch que você usa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22' # Ou outra versão compatível com seu projeto

      - name: Instalar dependências
        run: npm install

      - name: Fazer o build do projeto
        run: npm run build

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_host }}
          username: ${{ secrets.ftp_user }}
          password: ${{ secrets.ftp_password }}
          local-dir: dist/
          server-dir: / # Ajuste se necessário
